Add debianization for bullseye [REVPI-3198]
RevolutionPi/revpi-pitest pull request #3
Opened 2023-05-19 09:10 UTC by tboehler1

2023-05-19 09:15 UTC, tboehler1 commented
The [v1.4.0 tag](https://github.com/tboehler1/revpi-pitest/releases/tag/v1.4.0) as well as the [pristine-tar branch](https://github.com/tboehler1/revpi-pitest/tree/pristine-tar) can be seen on my fork: https://github.com/tboehler1/revpi-pitest

This would be how I imagine this repository to look like, too.

2023-05-22 13:30 UTC, naruxde requested changes

2023-05-23 09:16 UTC, naruxde approved these changes
Package build: OK
Update on target system: OK
```
Preparing to unpack .../pitest_1.4.0-1+revpi11+1_arm64.deb ...
Unpacking pitest (1.4.0-1+revpi11+1) over (1.3.1-1-221110+2-86ea91c9-1) ...
´´´

2023-05-23 14:43 UTC, tboehler1 commented
This is blocked by PR #7.

2023-05-24 07:12 UTC, iluminat23 approved these changes

2023-05-24 07:40 UTC, merged